export { default as Register } from './register/Register.jsx'
export { default as Home } from './home/Home.jsx'
export { default as Navbar } from './navbar/Navbar.jsx'
export { default as Dashboard } from './dashboard/Dashboard.jsx'
export { default as ActualitiesBox } from './actualities/ActualitiesBox.jsx'
export { default as NextSessionsBox } from './nextSessions/NextSessionsBox.jsx'
export { default as AddSupportCours } from './addSupportCours/AddSupportCours.jsx'
